services:

    dashy:
        image: lissy93/dashy:latest  
        container_name: dashy
        environment:
            - NODE_ENV=production
        ports:
            - "8200:8080"
        restart: unless-stopped
       
