services:

    dashy:
        image: lissy93/dashy:latest  
        container_name: my-dashboard              
        ports:
            - "8200:80"
        restart: unless-stopped     
       
